version: 0.2

phases: 
    install: 
        commands: 
            - echo Entered the install phase ...
            - apt-get update -y && apt-get upgrade -y
            - apt-get install openjdk-8-jdk -y
            - apt-get install maven -y
    build:
        commands: 
            - echo Entered the build phase ...
            - mvn clean install
artifacts:
    files:
        - target/account-example-0.0.1-SNAPSHOT.jar